# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60768ab6337f9891736eef0d6c4037fcde6859d49b24436a4538099b02de8726d2f5ee2c3a4638e79cb5ce51052a08acd0be68e21b43a2c227e8a2210219693a

test:
  secret_key_base: a84de0ef1dc59fa650ee7bc6b1f9f5e768db67891a99d4526f67fc25dcf22c1083a4cedfebebfecd9fe0899b9a6983c73a18892a07a0bfd092eb9724c1aef138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
